#!/usr/bin/env python3
"""Patch a dicomexportplan --test-mode TOPAS file into a project main.txt.

The generated test-mode file is already self-contained and carries the DICOM
gantry/couch angle plumbing in the same TOPAS parameter chain as BeamPosition.
This script removes the dicomexport water-box isocenter scorer and inserts
project snippets in its place.
"""

from __future__ import annotations

import argparse
from pathlib import Path


TOPAS_SETUP_START = "###         T O P A S    S E T U P"
WORLD_START = "###         W O R L D    S E T U P"
ISO_START = "###   I S O C E N T E R   S C O R E R"
NEXT_BLOCK = "###    GEOM.  B E A M   P O S I T I O N"
GENERATED_PREFIX = "# Generated "


def normalize_header(text: str) -> str:
    lines = []
    for line in text.splitlines():
        if line.startswith(GENERATED_PREFIX):
            lines.append("# Generated by dicomexportplan --test-mode; patched by tools/patch_topas_testmode.py")
        else:
            lines.append(line)
    return "\n".join(lines) + ("\n" if text.endswith("\n") else "")


def replace_isocenter_block(text: str, replacement: str) -> str:
    start = text.find(ISO_START)
    if start < 0:
        raise SystemExit(f"Could not find marker: {ISO_START}")

    block_start = text.rfind("##############################################", 0, start)
    if block_start < 0:
        raise SystemExit("Could not find start of isocenter scorer block")

    next_marker = text.find(NEXT_BLOCK, start)
    if next_marker < 0:
        raise SystemExit(f"Could not find marker: {NEXT_BLOCK}")

    block_end = text.rfind("##############################################", 0, next_marker)
    if block_end < 0 or block_end <= block_start:
        raise SystemExit("Could not find end of isocenter scorer block")

    return text[:block_start] + replacement.rstrip() + "\n\n" + text[block_end:]


def remove_topas_setup_block(text: str) -> str:
    start = text.find(TOPAS_SETUP_START)
    if start < 0:
        return text

    block_start = text.rfind("##############################################", 0, start)
    if block_start < 0:
        raise SystemExit("Could not find start of TOPAS setup block")

    next_marker = text.find(WORLD_START, start)
    if next_marker < 0:
        raise SystemExit(f"Could not find marker: {WORLD_START}")

    block_end = text.rfind("##############################################", 0, next_marker)
    if block_end < 0 or block_end <= block_start:
        raise SystemExit("Could not find end of TOPAS setup block")

    return text[:block_start] + text[block_end:]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Patch dicomexportplan --test-mode TOPAS into a DCPT main.txt."
    )
    parser.add_argument("testmode", type=Path, help="Input file from dicomexportplan --test-mode")
    parser.add_argument("output", type=Path, help="Patched TOPAS main.txt to write")
    parser.add_argument(
        "--insert",
        type=Path,
        action="append",
        required=True,
        help="Snippet to insert where the test-mode IsoBox/IsoScore block was removed. Repeatable.",
    )
    args = parser.parse_args()

    source = args.testmode.read_text()
    snippets = []
    for path in args.insert:
        snippets.append(path.read_text().strip())

    patched = normalize_header(remove_topas_setup_block(source))
    patched = replace_isocenter_block(patched, "\n\n".join(snippets))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(patched)


if __name__ == "__main__":
    main()
